import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#111827" },
  scrollView: { flex: 1 },

  // Auth
  authContainer: { flex: 1, backgroundColor: "#111827" },
  authScrollContent: { flexGrow: 1, justifyContent: "center", padding: 20 },
  authContent: { alignItems: "center" },
  authTitle: { fontSize: 32, fontWeight: "bold", color: "#ffffff", marginBottom: 8 },
  authSubtitle: { fontSize: 16, color: "#9ca3af", marginBottom: 50 },
  formContainer: { width: "100%", maxWidth: 400 },
  input: {
    width: "100%",
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 18,
    color: "#ffffff",
    fontSize: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#4b5563",
  },
  authButton: {
    width: "100%",
    backgroundColor: "#3b82f6",
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  authButtonDisabled: { opacity: 0.6 },
  authButtonText: { color: "#ffffff", fontSize: 16, fontWeight: "600" },
  switchContainer: { alignItems: "center", paddingVertical: 10 },
  switchText: { color: "#60a5fa", fontSize: 14 },
  errorContainer: {
    backgroundColor: "#7f1d1d",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    width: "100%",
    borderWidth: 1,
    borderColor: "#dc2626",
  },
  errorText: { color: "#fca5a5", textAlign: "center", fontSize: 14 },

  // Main
  header: { backgroundColor: "#1f2937", padding: 16, paddingBottom: 24 },
  headerTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 },
  title: { fontSize: 24, fontWeight: "bold", color: "#ffffff" },
  headerButtons: { flexDirection: "row", gap: 12 },
  logoutButton: { padding: 4 },
  balanceContainer: { flexDirection: "row", gap: 16, marginBottom: 24 },
  balanceCard: { flex: 1, backgroundColor: "rgba(55, 65, 81, 0.5)", borderRadius: 12, padding: 16 },
  balanceLabel: { fontSize: 12, color: "#9ca3af", marginBottom: 4 },
  balanceAmount: { fontSize: 18, fontWeight: "bold", color: "#ffffff" },
  portfolioCard: { backgroundColor: "rgba(55, 65, 81, 0.8)", borderRadius: 12, padding: 16 },
  portfolioHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  portfolioContent: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  portfolioValue: { fontSize: 20, fontWeight: "bold", color: "#ffffff" },
  returnContainer: { alignItems: "flex-end" },
  returnAmount: { fontSize: 12, fontWeight: "600" },
  returnPercent: { fontSize: 12, marginTop: 2 },
  viewHoldingsButton: { fontSize: 12, color: "#60a5fa", fontWeight: "600" },

  // Tabs - 세련된 디자인
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#1f2937",
    marginHorizontal: 16,
    marginBottom: 20,
    borderRadius: 16,
    padding: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  tab: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    minHeight: 70,
  },
  activeTab: {
    backgroundColor: "#3b82f6",
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabIcon: { fontSize: 24, marginBottom: 6 },
  tabText: { fontSize: 12, color: "#9ca3af", fontWeight: "600", textAlign: "center" },
  activeTabText: { color: "#ffffff" },

  // Stocks
  stocksSection: { padding: 16 },
  stocksHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  sectionTitle: { fontSize: 18, fontWeight: "600", color: "#ffffff" },

  // Stock Card
  stockCard: {
    backgroundColor: "#1f2937",
    borderRadius: 12,
    borderLeftWidth: 4,
    marginVertical: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  disabled: { opacity: 0.6 },
  stockContent: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16 },
  stockLeft: { flex: 1 },
  stockRight: { alignItems: "flex-end" },
  stockHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  stockName: { fontSize: 16, fontWeight: "600", color: "#ffffff", marginRight: 8 },
  stockCode: { fontSize: 12, color: "#9ca3af" },
  stockPrice: { fontSize: 20, fontWeight: "bold", color: "#ffffff" },
  stockPercent: { fontSize: 18, fontWeight: "bold", marginBottom: 4 },
  stockChangeContainer: { flexDirection: "row", alignItems: "center" },
  stockIcon: { marginRight: 4 },
  stockChange: { fontSize: 14, fontWeight: "500" },

  // Modal
  modalOverlay: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.5)", justifyContent: "center", alignItems: "center" },
  modalContent: { backgroundColor: "#1f2937", borderRadius: 16, padding: 24, width: "90%", maxHeight: "80%" },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: "#ffffff", textAlign: "center", marginBottom: 16 },
  priceContainer: { alignItems: "center", marginBottom: 24 },
  modalPrice: { fontSize: 24, fontWeight: "bold", color: "#ffffff", marginBottom: 4 },
  modalPriceChange: { fontSize: 14, fontWeight: "600" },
  inputContainer: { marginBottom: 16 },
  inputLabel: { fontSize: 14, color: "#d1d5db", marginBottom: 8 },
  modalInput: { backgroundColor: "#374151", borderRadius: 8, padding: 12, color: "#ffffff", fontSize: 16 },
  totalAmount: { fontSize: 16, color: "#d1d5db", textAlign: "center", marginBottom: 24 },
  modalButtons: { flexDirection: "row", gap: 12 },
  cancelButton: { flex: 1, backgroundColor: "#374151", borderRadius: 8, padding: 16, alignItems: "center" },
  cancelButtonText: { color: "#d1d5db", fontSize: 16, fontWeight: "600" },
  buyButton: { flex: 1, backgroundColor: "#3b82f6", borderRadius: 8, padding: 16, alignItems: "center" },
  buyButtonText: { color: "#ffffff", fontSize: 16, fontWeight: "600" },
  holdingsList: { maxHeight: 300, marginBottom: 16 },
  holdingItem: { backgroundColor: "#374151", borderRadius: 8, padding: 16, marginBottom: 12 },
  holdingHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  holdingName: { fontSize: 16, fontWeight: "600", color: "#ffffff", marginRight: 8 },
  holdingCode: { fontSize: 12, color: "#9ca3af", marginRight: 8 },
  marketBadge: { backgroundColor: "#4b5563", borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2 },
  marketBadgeText: { fontSize: 10 },
  holdingDetails: { gap: 4 },
  holdingText: { fontSize: 14, color: "#d1d5db" },
  holdingProfit: { fontSize: 14, fontWeight: "600" },
  closeButton: { backgroundColor: "#374151", borderRadius: 8, padding: 16, alignItems: "center" },
  closeButtonText: { color: "#d1d5db", fontSize: 16, fontWeight: "600" },
  emptyText: { color: "#9ca3af", textAlign: "center", fontSize: 16, paddingVertical: 32 },

  // Transaction History
  transactionItem: {
    backgroundColor: "#374151",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  transactionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  transactionName: { fontSize: 16, fontWeight: "600", color: "#ffffff" },
  transactionDate: { fontSize: 12, color: "#9ca3af" },
  transactionDetails: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  transactionInfo: { flex: 1 },
  transactionCode: { fontSize: 12, color: "#9ca3af", marginBottom: 4 },
  transactionQuantity: { fontSize: 14, color: "#d1d5db" },
  transactionAmount: { fontSize: 16, fontWeight: "600", color: "#ffffff", textAlign: "right" },
})
